/*
 * ARQUETIPOS DE SOLUCIÓN — Estudio Abimaru
 * Cada modelo del catálogo no es solo un estilo visual: es un arquetipo de solución
 * (problema, usuarios, procesos, capacidades, integraciones, datos, riesgos/controles,
 * ruta de implementación, complejidad, servicios relacionados).
 * Se muestra con progressive disclosure (modal "Ver solución").
 * complexity: essential | commercial | application | enterprise
 */
window.ARCHETYPES = {
  pixelvault: {
    label: "E-commerce especializado + comunidad + servicios",
    problem: "Vender productos de nicho en línea y fidelizar una comunidad, no solo mostrar un catálogo.",
    complexity: "commercial",
    users: ["Compradores", "Comunidad/aficionados", "Administrador de tienda"],
    processes: ["Catálogo y búsqueda", "Carrito y checkout", "Gestión de pedidos", "Contenido/comunidad"],
    capabilities: ["Catálogo con filtros", "Fichas de producto", "Carrito", "Estados de pedido", "Campañas y novedades"],
    integrations: ["Pasarela de pagos", "WhatsApp", "Correo transaccional", "Inventario", "Analítica"],
    dataTypes: ["Contacto", "Pedidos", "Preferencias"],
    risks: ["Pagos y fraude", "Stock desactualizado", "Datos de clientes"],
    controls: ["Pasarela certificada", "Validación de inventario", "Protección de datos y HTTPS"],
    implementationPath: ["Catálogo", "Carrito y pagos", "Gestión de pedidos", "Fidelización"],
    relatedServices: ["Tienda Virtual", "Custom Application Prototype"],
  },
  nexora: {
    label: "Catálogo técnico + configurador + soporte",
    problem: "Presentar productos y servicios técnicos y captar solicitudes de diagnóstico o cotización.",
    complexity: "commercial",
    users: ["Clientes", "Equipo comercial", "Soporte técnico"],
    processes: ["Catálogo técnico", "Configuración de equipos", "Agenda/diagnóstico", "Contacto"],
    capabilities: ["Catálogo", "Configurador interactivo", "Sección de servicios", "Formularios de contacto"],
    integrations: ["WhatsApp", "Correo", "Agenda/calendario", "CRM", "Analítica"],
    dataTypes: ["Contacto", "Solicitudes de servicio"],
    risks: ["Expectativa de disponibilidad", "Datos de contacto"],
    controls: ["Textos claros de alcance", "Privacidad y consentimiento", "Sin promesas de garantía"],
    implementationPath: ["Catálogo y servicios", "Configurador", "Captura de solicitudes", "Integración CRM"],
    relatedServices: ["Página Esencial", "Custom Application Prototype"],
  },
  atelier: {
    label: "Portafolio premium + cotización personalizada",
    problem: "Mostrar trabajo a la medida con nivel editorial y convertir el interés en solicitudes de cotización.",
    complexity: "commercial",
    users: ["Clientes potenciales", "Estudio/taller"],
    processes: ["Portafolio por colecciones", "Proceso de trabajo", "Solicitud de cotización"],
    capabilities: ["Galería de proyectos", "Detalle de proyecto", "Formulario de cotización", "Narrativa de marca"],
    integrations: ["WhatsApp", "Correo", "Analítica"],
    dataTypes: ["Contacto", "Detalles del proyecto solicitado"],
    risks: ["Uso de imágenes/derechos", "Datos de contacto"],
    controls: ["Assets propios o con licencia", "Privacidad", "Alcance conceptual claro"],
    implementationPath: ["Portafolio", "Proceso y detalle", "Cotización", "Seguimiento"],
    relatedServices: ["Catálogo Comercial", "Digital Solution Blueprint"],
  },
  maru: {
    label: "Tienda visual + catálogo + conversión",
    problem: "Vender moda con una experiencia visual atractiva que impulse la conversión.",
    complexity: "commercial",
    users: ["Compradores", "Administrador de tienda"],
    processes: ["Catálogo por categorías", "Bolsa de compra", "Checkout", "Pedidos"],
    capabilities: ["Categorías por público", "Fichas con precios", "Bolsa de compra", "Diseño editorial"],
    integrations: ["Pasarela de pagos", "WhatsApp", "Envíos", "Analítica"],
    dataTypes: ["Contacto", "Pedidos", "Direcciones de envío"],
    risks: ["Pagos", "Datos personales", "Expectativa de envíos"],
    controls: ["Pasarela certificada", "Protección de datos", "Políticas de envío claras"],
    implementationPath: ["Catálogo", "Bolsa/checkout", "Pagos y envíos", "Optimización de conversión"],
    relatedServices: ["Tienda Virtual"],
  },
  vitalis: {
    label: "Catálogo regulado + flujos sensibles + transparencia",
    problem: "Digitalizar un catálogo de salud con responsabilidad, sin prometer lo que no se puede cumplir.",
    complexity: "commercial",
    users: ["Clientes/pacientes", "Farmacia/tienda"],
    processes: ["Catálogo por categorías", "Flujo de receta (ilustrativo)", "Pedido", "Atención"],
    capabilities: ["Catálogo", "Etiquetas Rx/venta libre", "Pedido por WhatsApp", "Avisos de transparencia"],
    integrations: ["WhatsApp", "Correo", "Analítica"],
    dataTypes: ["Contacto", "Pedidos", "Datos sensibles (salud) — evitar en demo"],
    risks: ["Claims médicos/regulatorios", "Datos de salud", "Expectativa de asesoría"],
    controls: ["Avisos claros (no es farmacia real)", "No recolectar datos sensibles sin base legal", "Sin asesoría médica"],
    implementationPath: ["Catálogo y avisos", "Flujo de pedido", "Cumplimiento y privacidad", "Operación"],
    relatedServices: ["Catálogo Comercial", "Assurance & Launch Review"],
  },
  prospera: {
    label: "Simulación financiera + educación + escenarios",
    problem: "Ayudar a decidir con simuladores claros y educación, sin ofrecer productos financieros reales.",
    complexity: "commercial",
    users: ["Visitantes", "Equipo comercial"],
    processes: ["Simulación de crédito/ahorro", "Educación financiera", "Captura de solicitudes"],
    capabilities: ["Simuladores interactivos", "Escenarios comparados", "Secciones de confianza", "CTA de contacto"],
    integrations: ["WhatsApp", "Correo", "CRM", "Analítica"],
    dataTypes: ["Contacto", "Parámetros de simulación (no sensibles)"],
    risks: ["Claims financieros", "Expectativa de aprobación", "Datos personales"],
    controls: ["Avisos: valores ilustrativos, no es entidad financiera", "Sin consulta de score real", "Privacidad"],
    implementationPath: ["Simuladores", "Educación", "Captura de leads", "Integración CRM"],
    relatedServices: ["Landing (Página Esencial)", "Digital Solution Blueprint"],
  },
  nucleo: {
    label: "Operación interna + clientes + pipeline + reportes",
    problem: "Ordenar la operación interna (clientes, negocios, tareas) cuando las hojas de cálculo ya no alcanzan.",
    complexity: "application",
    users: ["Equipo interno", "Administradores", "Dirección"],
    processes: ["Gestión de contactos", "Pipeline de negocios", "Tareas", "Reportes"],
    capabilities: ["Panel con métricas", "Contactos", "Tablero de negocios", "Reportes visuales"],
    integrations: ["Autenticación", "Correo", "Calendario", "APIs internas", "Base de datos"],
    dataTypes: ["Clientes", "Negocios", "Actividad interna"],
    risks: ["Acceso y permisos", "Datos comerciales", "Continuidad"],
    controls: ["Roles y permisos", "Respaldo/recuperación", "Auditoría y trazabilidad"],
    implementationPath: ["Modelo de datos", "Vistas y flujos", "Permisos", "Reportes y despliegue"],
    relatedServices: ["Custom Application Prototype", "Architecture Assessment"],
  },
  vianova: {
    label: "Marketplace + originación + comparación + financiación",
    problem: "Orquestar un ecosistema complejo (buscar, comparar, simular, solicitar, proteger) en una sola ruta.",
    complexity: "enterprise",
    users: ["Clientes", "Asesores", "Aliados (aseguradoras/financieras)", "Operación"],
    processes: ["Marketplace", "Comparación", "Simulación financiera", "Originación de solicitud", "Cartera y seguros"],
    capabilities: ["Filtros y comparador", "Cockpit financiero (escenarios)", "Crédito por monto", "Solicitud multipaso", "Compra de cartera", "Seguros"],
    integrations: ["Pasarela/originación", "Aseguradoras", "Buró/score (real: con permisos)", "CRM", "APIs de aliados"],
    dataTypes: ["Contacto", "Datos financieros (real: sensibles)", "Solicitudes"],
    risks: ["Datos financieros sensibles", "Claims de aprobación", "Integraciones críticas", "Cumplimiento"],
    controls: ["Avisos: simulación ilustrativa, sin aprobación", "Clasificación y protección de datos", "Contratos y trazabilidad"],
    implementationPath: ["Marketplace y comparación", "Simuladores", "Originación", "Integraciones (seguros/financiación)", "Operación"],
    relatedServices: ["Architecture Assessment", "Serverless & Cloud Blueprint", "Custom Application Prototype"],
  },
};

/* Etiquetas legibles para complejidad */
window.ARCHETYPE_COMPLEXITY = {
  essential: "Esencial",
  commercial: "Comercial",
  application: "Aplicación",
  enterprise: "Empresarial",
};
